
project_id = "yieihrvcbshzmxieflsv"

[realtime]
enabled = true

[api]
enabled = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
