
project_id = "yieihrvcbshzmxieflsv"

[api]
enabled = true

[auth]
enabled = true

[db]
enabled = true

[edges]
enabled = true

[[edges.routes]]
path = "/stripe-webhook"
method = "POST"
verify_jwt = false

[[edges.routes]]
path = "/create-checkout"
method = "POST"
verify_jwt = true

[[edges.routes]]
path = "/customer-portal"
method = "POST"
verify_jwt = true

[[edges.routes]]
path = "/check-subscription"
method = "GET"
verify_jwt = true
